"""Advisory insight reports over a domain specialist (Phase V3, ADR-006/ADR-014).

Mirrors the legacy v0 insight contract (``git show legacy/v0:mira/schema.py``:
summary / insights with topic+detail+evidence / adjustments / confidence /
caveats) as **plain frozen dataclasses** — core deps only, no pydantic.

A report is generated by running a small fixed battery of representative
queries (wash status, TLH candidates, allocation) through a specialist and
converting each grounded :class:`~mira.orchestration.specialist_scaffold.
SpecialistResult` into an :class:`Insight`. The report is **ADVISORY ONLY**:
suggestions are phrased as observations/considerations, never instructions to
trade, and :data:`ADVISORY_DISCLAIMER` always lands in ``caveats``.

Confidence is a deterministic structural heuristic, not a judgment of semantic
quality:

* every battery query produced a grounded (provenance-carrying), error-free
  observation → ``"medium"``;
* any tool error, specialist error, or ungrounded observation → ``"low"``;
* ``"high"`` is **never** produced — this heuristic has no model in the loop
  to earn it; a model-scored path may claim it later.
"""

from __future__ import annotations

import json
from collections.abc import Callable, Mapping
from dataclasses import dataclass, field
from typing import Any, Literal

from mira.orchestration.agent_cards import AgentCardRegistry
from mira.orchestration.specialist_scaffold import SpecialistResult, SpecialistSubgraph

Confidence = Literal["low", "medium", "high"]

ADVISORY_DISCLAIMER = (
    "Advisory only: these are observations for consideration, never instructions "
    "to trade. All figures come from the read-only Vantage engine tools — Mira "
    "performs no portfolio math."
)

# Fixed battery of representative advisory queries. Each phrase deterministically
# maps to one vantage.* tool via the advisor's query-inference hook.
DEFAULT_INSIGHT_QUERIES: tuple[str, ...] = (
    "What is the household wash-sale status?",
    "Which lots are tax-loss-harvest candidates?",
    "What is the current asset allocation?",
)

# Battery for the trade-review report: round-trip summary + the defensible
# edges/leaks. Both phrases route to vantage.* trade-analytics tools.
TRADE_REVIEW_QUERIES: tuple[str, ...] = (
    "Show my closed round-trips record.",  # → vantage.roundtrips (summary)
    "What are my trading edges and leaks?",  # → vantage.trade_stats (notable)
)

_MAX_FALLBACK_DETAIL = 200


@dataclass(frozen=True, slots=True)
class Insight:
    """One concrete observation, grounded in a tool result."""

    topic: str
    detail: str
    evidence: str
    provenance: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "topic": self.topic,
            "detail": self.detail,
            "evidence": self.evidence,
            "provenance": dict(self.provenance),
        }


@dataclass(frozen=True, slots=True)
class InsightReport:
    """The advisory report an insight run produces. Never an instruction to trade."""

    summary: str
    observations: tuple[Insight, ...]
    suggestions: tuple[str, ...]
    confidence: Confidence
    caveats: str
    generated_for: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "summary": self.summary,
            "observations": [insight.to_dict() for insight in self.observations],
            "suggestions": list(self.suggestions),
            "confidence": self.confidence,
            "caveats": self.caveats,
            "generated_for": self.generated_for,
        }


def _topic_for(query: str) -> str:
    """Deterministic topic label from the battery query's intent."""
    lowered = query.lower()
    if (
        "learned" in lowered
        or "edge" in lowered
        or "leak" in lowered
        or "lesson" in lowered
        or "trade best" in lowered
        or "profit factor" in lowered
        or "win rate" in lowered
        or "round-trip" in lowered
        or "round trip" in lowered
        or "roundtrip" in lowered
    ):
        return "trade_review"
    if "tlh" in lowered or "candidate" in lowered or "tax-loss" in lowered:
        return "tlh_candidates"
    if "wash" in lowered or "harvest" in lowered:
        return "wash_status"
    if "allocation" in lowered or "drift" in lowered:
        return "allocation"
    if "holding" in lowered or "position" in lowered:
        return "positions"
    return "observation"


def _detail_for(topic: str, answer: Mapping[str, Any]) -> str:
    """Short deterministic summary of the answer dict, per intent."""
    if topic == "wash_status" and isinstance(answer.get("wash"), Mapping):
        wash = answer["wash"]
        blocked = sorted(
            sym for sym, status in wash.items()
            if isinstance(status, Mapping) and status.get("blocked")
        )
        detail = f"{len(blocked)} of {len(wash)} symbol(s) wash-blocked"
        return f"{detail}: {', '.join(blocked)}" if blocked else detail
    if topic == "tlh_candidates" and isinstance(answer.get("candidates"), list):
        candidates = answer["candidates"]
        by_status: dict[str, int] = {}
        for cand in candidates:
            status = str(cand.get("status", "?")) if isinstance(cand, Mapping) else "?"
            by_status[status] = by_status.get(status, 0) + 1
        breakdown = ", ".join(f"{n} {s}" for s, n in sorted(by_status.items()))
        return f"{len(candidates)} loss lot(s)" + (f" ({breakdown})" if breakdown else "")
    if topic == "allocation" and isinstance(answer.get("by_class"), Mapping):
        parts = []
        for cls, entry in sorted(answer["by_class"].items()):
            pct = entry.get("pct") if isinstance(entry, Mapping) else entry
            parts.append(f"{cls} {round(float(pct or 0.0), 1)}%")
        return "allocation: " + ", ".join(parts)
    if topic == "positions" and isinstance(answer.get("positions"), list):
        return f"{len(answer['positions'])} position(s) held"
    if topic == "trade_review":
        summary = answer.get("summary")
        if isinstance(summary, Mapping):
            return (
                f"{summary.get('count', 0)} closed round-trips: win-rate "
                f"{_pct(summary.get('win_rate'))}, profit factor "
                f"{round(float(summary.get('profit_factor', 0) or 0), 2)}, "
                f"avg hold {round(float(summary.get('avg_holding_days', 0) or 0), 1)}d"
            )
        notable = answer.get("notable")
        if isinstance(notable, list):
            sig = [b for b in notable if isinstance(b, Mapping) and b.get("significant") is True]
            thin = len(notable) - len(sig)
            base = answer.get("baseline_win_rate")
            head = f"baseline win-rate {_pct(base)}" if base is not None else "no baseline yet"
            return (
                f"{head}; {len(sig)} defensible edge/leak(s)"
                + (f", {thin} seen but too thin to count" if thin else "")
            )
    return json.dumps(dict(answer), sort_keys=True, default=str)[:_MAX_FALLBACK_DETAIL]


def _pct(value: Any) -> str:
    try:
        return f"{round(float(value) * 100)}%"
    except (TypeError, ValueError):
        return "n/a"


def _suggestions_for(topic: str, answer: Mapping[str, Any]) -> list[str]:
    """Advisory phrasing derived from the answer — observations, never instructions."""
    out: list[str] = []
    if topic == "wash_status" and isinstance(answer.get("wash"), Mapping):
        blocked = sorted(
            sym for sym, status in answer["wash"].items()
            if isinstance(status, Mapping) and status.get("blocked")
        )
        if blocked:
            out.append(
                f"Observation: {', '.join(blocked)} currently wash-blocked; the engine "
                "reports when each window clears — worth reviewing before considering "
                "any harvest."
            )
    if topic == "tlh_candidates" and isinstance(answer.get("candidates"), list):
        clear = [
            cand for cand in answer["candidates"]
            if isinstance(cand, Mapping) and cand.get("status") == "clear"
        ]
        if clear:
            out.append(
                f"Observation: {len(clear)} loss lot(s) are marked clear by the engine "
                "with a mapped replacement — a consideration to review, not a trade "
                "instruction."
            )
    if topic == "trade_review" and isinstance(answer.get("notable"), list):
        base = answer.get("baseline_win_rate")
        for bucket in answer["notable"]:
            if not isinstance(bucket, Mapping) or bucket.get("significant") is not True:
                continue  # never surface a thin bucket as a suggestion
            dim = str(bucket.get("dimension", "")).replace("_", " ")
            val = str(bucket.get("value", ""))
            n = bucket.get("n")
            wr = _pct(bucket.get("win_rate"))
            verb = "win more" if bucket.get("kind") == "edge" else "win less"
            out.append(
                f"Observation: you {verb} on {val} {dim} — {wr} vs {_pct(base)} baseline "
                f"(n={n}); a grounded pattern in your own round-trips to consider, not a "
                "trade instruction."
            )
    return out


def _grounded(answer: Mapping[str, Any]) -> bool:
    prov = answer.get("provenance")
    return (
        isinstance(prov, Mapping)
        and bool(prov.get("source_type"))
        and bool(prov.get("source_id"))
    )


def _consume_result(
    query: str,
    result: SpecialistResult,
) -> tuple[Insight | None, list[str]]:
    """One battery result → (Insight or None, caveat entries)."""
    topic = _topic_for(query)
    if result.error:
        return None, [f"{topic}: specialist error — {result.error}"]
    answer = result.answer if isinstance(result.answer, Mapping) else {}
    if answer.get("status") == "tool_error":
        detail = str(answer.get("detail", ""))
        tool = str(answer.get("tool", "unknown tool"))
        return None, [f"{topic}: tool_error from {tool} — {detail}"]
    insight = Insight(
        topic=topic,
        detail=_detail_for(topic, answer),
        evidence=json.dumps(dict(answer), sort_keys=True, default=str),
        provenance=dict(answer.get("provenance") or {}) if isinstance(
            answer.get("provenance"), Mapping
        ) else {},
    )
    return insight, []


def generate_insight_report(
    specialist: SpecialistSubgraph,
    *,
    queries: tuple[str, ...] | None = None,
    thread_id: str = "insights",
) -> InsightReport:
    """Run the query battery through ``specialist`` and assemble the advisory report.

    Deterministic end to end: fixed battery order, per-query namespaced thread
    ids (so loop state never bleeds between battery items), structural
    confidence heuristic (see module docstring), and the fixed
    :data:`ADVISORY_DISCLAIMER` always appended to ``caveats``.
    """
    battery = tuple(queries) if queries else DEFAULT_INSIGHT_QUERIES
    domain = specialist.domain_spec.domain_id

    observations: list[Insight] = []
    suggestions: list[str] = []
    error_caveats: list[str] = []
    for index, query in enumerate(battery):
        result = specialist.invoke(query, thread_id=f"{thread_id}:{index}")
        insight, caveats = _consume_result(query, result)
        error_caveats.extend(caveats)
        if insight is not None:
            observations.append(insight)
            suggestions.extend(_suggestions_for(insight.topic, result.answer))

    all_grounded = bool(observations) and all(
        insight.provenance.get("source_type") and insight.provenance.get("source_id")
        for insight in observations
    )
    confidence: Confidence = (
        "medium" if not error_caveats and all_grounded and len(observations) == len(battery)
        else "low"
    )

    summary = (
        f"{len(observations)} grounded observation(s) from {len(battery)} advisory "
        f"queries for domain '{domain}'; confidence {confidence}."
    )
    caveats = "\n".join([*error_caveats, ADVISORY_DISCLAIMER])
    return InsightReport(
        summary=summary,
        observations=tuple(observations),
        suggestions=tuple(suggestions),
        confidence=confidence,
        caveats=caveats,
        generated_for=domain,
    )


def generate_trade_review_report(
    specialist: SpecialistSubgraph,
    *,
    thread_id: str = "trade_review",
) -> InsightReport:
    """Advisory trade-review over round-trip summary + defensible edges/leaks.

    Runs :data:`TRADE_REVIEW_QUERIES` (round-trip record → win-rate/profit-factor
    summary; edges/leaks → the *significant* notable buckets) through the
    advisor. Advisory only: suggestions phrase each significant bucket as an
    observation (never an instruction), and a small-n / non-significant bucket is
    NEVER surfaced as an edge (:func:`_suggestions_for` filters on
    ``significant is True``).

    Confidence is honest about sample size: ``medium`` only when every battery
    query grounded AND at least one defensible edge/leak exists; ``low``
    otherwise (thin data, tool error, or no significant bucket). ``high`` is
    never produced — same structural heuristic as
    :func:`generate_insight_report`.
    """
    battery = TRADE_REVIEW_QUERIES
    domain = specialist.domain_spec.domain_id

    observations: list[Insight] = []
    suggestions: list[str] = []
    error_caveats: list[str] = []
    significant_edges = 0
    thin_seen = 0
    for index, query in enumerate(battery):
        result = specialist.invoke(query, thread_id=f"{thread_id}:{index}")
        insight, caveats = _consume_result(query, result)
        error_caveats.extend(caveats)
        if insight is None:
            continue
        observations.append(insight)
        suggestions.extend(_suggestions_for(insight.topic, result.answer))
        answer = result.answer if isinstance(result.answer, Mapping) else {}
        notable = answer.get("notable")
        if isinstance(notable, list):
            for bucket in notable:
                if not isinstance(bucket, Mapping):
                    continue
                if bucket.get("significant") is True:
                    significant_edges += 1
                else:
                    thin_seen += 1

    all_grounded = bool(observations) and all(
        insight.provenance.get("source_type") and insight.provenance.get("source_id")
        for insight in observations
    )
    confidence: Confidence = (
        "medium"
        if not error_caveats
        and all_grounded
        and len(observations) == len(battery)
        and significant_edges > 0
        else "low"
    )

    caveat_lines = list(error_caveats)
    if thin_seen:
        caveat_lines.append(
            f"{thin_seen} condition(s) separated from baseline but had too few "
            "trades to be defensible — not reported as edges (small-n honesty)."
        )
    if significant_edges == 0:
        caveat_lines.append(
            "No statistically defensible edge or leak yet — win-rate differences "
            "seen are within noise for the current sample."
        )

    summary = (
        f"Trade review for domain '{domain}': {significant_edges} defensible "
        f"edge/leak(s) from {len(observations)} grounded observation(s); "
        f"confidence {confidence}."
    )
    caveats = "\n".join([*caveat_lines, ADVISORY_DISCLAIMER])
    return InsightReport(
        summary=summary,
        observations=tuple(observations),
        suggestions=tuple(suggestions),
        confidence=confidence,
        caveats=caveats,
        generated_for=f"{domain}:trade_review",
    )


def cached_insights_provider(
    registry: AgentCardRegistry,
) -> Callable[[str, bool], dict[str, Any] | None]:
    """In-memory ``{domain: report}`` cache over the insight generators.

    The provider the composition root hands to the service's ``/insights`` route:
    ``provider(domain, refresh)`` returns the report dict for a registered
    domain (generated lazily on first request; a scheduled job hitting the
    endpoint periodically keeps it warm), regenerates when ``refresh`` is true,
    and returns None for a domain with no registered card (→ 404).

    A ``trade_review`` suffix selects the trade-review battery instead of the
    default advisory battery: ``?domain=advisor:trade_review`` (or the bare alias
    ``?domain=trade_review``, which resolves the advisor) yields
    :func:`generate_trade_review_report` — the round-trip summary + defensible
    edges/leaks, with small-n buckets held out of the edges.
    """
    cache: dict[str, dict[str, Any]] = {}
    _TRADE_REVIEW = "trade_review"

    def provider(domain: str, refresh: bool = False) -> dict[str, Any] | None:
        known = {card.name for card in registry.cards()}
        # Resolve the trade-review virtual domain: bare alias → advisor; or the
        # "<domain>:trade_review" suffix form.
        base_domain = domain
        trade_review = False
        if domain == _TRADE_REVIEW:
            base_domain, trade_review = "advisor", True
        elif domain.endswith(f":{_TRADE_REVIEW}"):
            base_domain, trade_review = domain[: -len(f":{_TRADE_REVIEW}")], True
        if base_domain not in known:
            return None
        if refresh or domain not in cache:
            specialist = registry.resolve(base_domain)
            report = (
                generate_trade_review_report(specialist, thread_id=f"insights:{domain}")
                if trade_review
                else generate_insight_report(specialist, thread_id=f"insights:{domain}")
            )
            cache[domain] = report.to_dict()
        return cache[domain]

    return provider


__all__ = [
    "ADVISORY_DISCLAIMER",
    "DEFAULT_INSIGHT_QUERIES",
    "TRADE_REVIEW_QUERIES",
    "Confidence",
    "Insight",
    "InsightReport",
    "cached_insights_provider",
    "generate_insight_report",
    "generate_trade_review_report",
]
