"""Domain-agent scaffold generator (ADR-016) — the ``mira-scaffold`` console script.

``mira-scaffold new-domain <name> --tool-prefix <p>`` generates every artifact a
new domain specialist needs, with the platform invariants wired at creation:

* a connector skeleton with typed, **fail-closed** entitlement-bearing tool specs
  (ADR-020/031) — or, with ``--domain-kind mcp``, a specialist bound to the
  declared MCP server registry (``MCP_SERVERS`` env, ADR-020) instead of a local
  connector;
* a specialist module built on the shared subgraph scaffold (ADR-014) with a
  ``DomainSpec``, a representative-query placeholder, a ``query_inference`` hook
  stub, and the agent-card snippet + registration instructions in its docstring
  (ADR-035);
* minimal **passing** tests over the skeleton (protocol conformance, DomainSpec
  identity, empty-allowlist fail-closed);
* the ``specs/<name>-specialist/`` spec/plan/tasks trio; and
* an ``evals/goldens/<name>.jsonl.example`` golden stub for the ADR-045 gate
  (rename to ``.jsonl`` once the representative query answers end-to-end).

Generation is template-based (strings embedded in this module — no external
template files, no network) and **refuses to overwrite**: if any target path
exists, nothing is written and the command fails loudly.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from string import Template

_NAME_RE = re.compile(r"[a-z][a-z0-9_]*")
_PREFIX_RE = re.compile(r"[a-z][a-z0-9_\-\.]*\.")


class ScaffoldError(Exception):
    """Raised when generation cannot proceed (bad input or existing files)."""


# ---------------------------------------------------------------------------
# Templates (string.Template; $-substitution never collides with Python braces)
# ---------------------------------------------------------------------------

_CONNECTOR_TEMPLATE = '''"""${title} source connector skeleton — generated by mira-scaffold (ADR-016, ADR-020).

An anti-corruption adapter (ADR-020) for the ${name} source. The sample
``lookup`` capability is functional so the generated tests pass as-is; replace
the sample data path with the real source shape (see ``mira.connectors.ledger``
for the reference: parse once up front, serve uniform attributed records).

TODO(${name}): parse the real source into a typed document and extend
``tool_specs``/``query`` per operation. Keep every tool entitlement-bearing
(fail-closed — a blank entitlement is rejected by the contract).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from mira.connectors.base import Provenance, SourceDescription, SourceRecord
from mira.connectors.mcp_export import ToolSpec

_CAP_LOOKUP = "lookup"


@dataclass(slots=True)
class ${class_name}Connector:
    """${title} adapter for :class:`~mira.connectors.base.SourceConnector`."""

    SOURCE_TYPE: str = field(default="${source_type}", init=False)
    source_id: str

    def describe(self) -> SourceDescription:
        """Advertise the ${name} source type and its read capabilities."""
        return SourceDescription(
            source_type=self.SOURCE_TYPE, capabilities=(_CAP_LOOKUP,)
        )

    def tool_specs(self) -> list[ToolSpec]:
        """Declare read-only, entitlement-bearing MCP tools (ADR-031, fail-closed)."""
        return [
            ToolSpec(
                capability=_CAP_LOOKUP,
                required_entitlement="connector:${source_type}:lookup",
                description="TODO(${name}): describe the lookup operation",
                input_schema={
                    "type": "object",
                    "properties": {"query": {"type": "string"}},
                    "required": ["query"],
                    "additionalProperties": False,
                },
            ),
        ]

    def query(self, request: Any) -> list[SourceRecord]:
        """Serve one uniform attributed record for a lookup request.

        TODO(${name}): execute the real source lookup; the sample echoes the
        request so the generated tests exercise the full record shape.
        """
        payload = getattr(request, "payload", request)
        if not isinstance(payload, dict) or "query" not in payload:
            raise ValueError("${name} query requires a 'query' field")
        return [
            SourceRecord(
                provenance=Provenance(
                    source_type=self.SOURCE_TYPE, source_id=self.source_id
                ),
                payload={"status": "sample", "query": str(payload["query"])},
            )
        ]


def build_connector(source_id: str = "${name}-sample") -> ${class_name}Connector:
    """Build a ${name} connector attributed to ``source_id``."""
    return ${class_name}Connector(source_id=source_id)
'''

_SPECIALIST_DOCSTRING_CONNECTOR = """${title} domain specialist — generated by mira-scaffold (ADR-016, ADR-014).

Built on the shared specialist-subgraph scaffold: a
:class:`~mira.orchestration.specialist_scaffold.DomainSpec`, a tool allow-list
(``${prefix}*``), and a per-domain ``query_inference`` hook — no new LangGraph
wiring. Tools come from the generated ``mira.connectors.${name}`` connector via
``mira.connectors.export_tools`` bound to in-process handlers (see
``specialists/demo.py`` for the reference wiring).

Registration (agent card + registry; see specialists/demo.py):

    from mira.orchestration.agent_cards import card_for_domain

    ${upper}_CARD = card_for_domain(
        ${upper}_DOMAIN,
        description="TODO(${name}): one-line capability description",
        keywords=("${name}",),  # TODO(${name}): routing keywords
    )
    registry.register(
        ${upper}_CARD, lambda: build_${name}_specialist(registered_tools)
    )

Golden baseline (ADR-045): fill in ``evals/goldens/${name}.jsonl.example`` and
rename it to ``${name}.jsonl`` once the representative query answers
end-to-end — the agent is eval-gated before it is routable.
"""

_SPECIALIST_DOCSTRING_MCP = """${title} domain specialist — generated by mira-scaffold (ADR-016, ADR-014).

Built on the shared specialist-subgraph scaffold: a
:class:`~mira.orchestration.specialist_scaffold.DomainSpec`, a tool allow-list
(``${prefix}*``), and a per-domain ``query_inference`` hook — no new LangGraph
wiring. This domain binds **remote MCP tools** instead of a local connector:
declare the server in the ``MCP_SERVERS`` env registry
(``mira.connectors.mcp_registry``), discover its tools at wiring time, and bind
the ``${prefix}*`` subset as
:class:`~mira.orchestration.specialist_scaffold.RegisteredTool` handlers.

Registration (agent card + registry; see specialists/demo.py):

    from mira.orchestration.agent_cards import card_for_domain

    ${upper}_CARD = card_for_domain(
        ${upper}_DOMAIN,
        description="TODO(${name}): one-line capability description",
        keywords=("${name}",),  # TODO(${name}): routing keywords
    )
    registry.register(
        ${upper}_CARD, lambda: build_${name}_specialist(mcp_registered_tools)
    )

Golden baseline (ADR-045): fill in ``evals/goldens/${name}.jsonl.example`` and
rename it to ``${name}.jsonl`` once the representative query answers
end-to-end — the agent is eval-gated before it is routable.
"""

_SPECIALIST_BODY = '''

from __future__ import annotations

from typing import Any

from mira.orchestration.reasoning import ReasoningBudget
from mira.orchestration.specialist_scaffold import (
    DomainSpec,
    RegisteredTool,
    SpecialistSubgraph,
    build_specialist_subgraph,
)

${upper}_DOMAIN = DomainSpec(
    domain_id="${name}",
    tool_prefixes=frozenset({"${prefix}"}),
)

REPRESENTATIVE_${upper}_QUERY = (
    "TODO(${name}): the representative question this specialist answers end-to-end"
)


def _infer_${name}_query(
    action: str,
    registry: dict[str, RegisteredTool],
) -> dict[str, Any] | None:
    """Per-domain query-inference hook stub.

    TODO(${name}): dispatch the right ${prefix}* tool when ``action`` names the
    representative question's topic (see ``specialists/finance.py`` for the
    reference shape). Returning ``None`` falls through to the scaffold's
    structured noop — never guess a tool call.
    """
    return None


def build_${name}_specialist(
    tools: list[RegisteredTool],
    *,
    budget: ReasoningBudget | None = None,
) -> SpecialistSubgraph:
    """Return the ${name} specialist subgraph scoped to ${prefix}* tools."""
    return build_specialist_subgraph(
        ${upper}_DOMAIN,
        tools,
        budget=budget,
        query_inference=_infer_${name}_query,
    )
'''

_CONNECTOR_TEST_TEMPLATE = '''"""Generated tests for the ${name} connector skeleton (mira-scaffold, ADR-016).

These pass over the generated skeleton as-is; extend them alongside the real
source implementation (see ``tests/test_ledger_connector.py`` for the shape).
"""

from __future__ import annotations

from mira.connectors import SourceConnector, SourceRecord, export_tools
from mira.connectors.${name} import ${class_name}Connector, build_connector


def test_connector_conforms_to_source_connector_protocol() -> None:
    connector = build_connector()
    assert isinstance(connector, SourceConnector)
    description = connector.describe()
    assert description.source_type == "${source_type}"
    assert "lookup" in description.capabilities


def test_tools_export_with_prefix_and_fail_closed_entitlements() -> None:
    contracts = export_tools(build_connector())
    assert contracts
    for contract in contracts:
        assert contract.name.startswith("${prefix}")
        assert contract.required_entitlement  # fail-closed: never blank
        assert contract.readOnlyHint


def test_sample_lookup_returns_attributed_record() -> None:
    records = build_connector().query({"query": "sample"})
    assert isinstance(records[0], SourceRecord)
    assert records[0].provenance.source_type == "${source_type}"
    assert records[0].payload["status"] == "sample"


def test_malformed_request_is_rejected() -> None:
    connector = build_connector()
    try:
        connector.query({"unexpected": True})
    except ValueError:
        return
    raise AssertionError("malformed request must raise, never answer silently")
'''

_SPECIALIST_TEST_TEMPLATE = '''"""Generated tests for the ${name} specialist (mira-scaffold, ADR-016).

These pass over the generated skeleton as-is: DomainSpec identity, shared-
scaffold construction, and the fail-closed allow-list invariants every
specialist must keep.
"""

from __future__ import annotations

from mira.orchestration.specialist_scaffold import (
    DomainSpec,
    SpecialistSubgraph,
    build_specialist_subgraph,
)
from mira.orchestration.specialists.${name} import (
    ${upper}_DOMAIN,
    REPRESENTATIVE_${upper}_QUERY,
    build_${name}_specialist,
)


def test_domain_spec_identity() -> None:
    assert ${upper}_DOMAIN.domain_id == "${name}"
    assert ${upper}_DOMAIN.tool_prefixes == frozenset({"${prefix}"})


def test_specialist_builds_from_shared_scaffold() -> None:
    specialist = build_${name}_specialist([])
    assert isinstance(specialist, SpecialistSubgraph)
    assert specialist.domain_spec is ${upper}_DOMAIN


def test_empty_allowlist_fails_closed() -> None:
    empty = build_specialist_subgraph(
        DomainSpec(domain_id="${name}", tool_prefixes=frozenset()), []
    )
    result = empty.invoke(REPRESENTATIVE_${upper}_QUERY, thread_id="scaffold-closed")
    assert result.error == "no tools allowed for domain"


def test_cross_domain_tool_calls_are_rejected() -> None:
    specialist = build_${name}_specialist([])
    result = specialist.invoke(
        "cross-domain :tool:other.forbidden:", thread_id="scaffold-cross"
    )
    assert result.error
    assert "not allowed for domain" in result.error
'''

_SPEC_TEMPLATE = """# ${title} Specialist Subgraph — Spec

> **Feature slug:** ${name}-specialist
> Siblings: [`plan.md`](./plan.md) (files/steps/ADRs/edge-cases) · [`tasks.md`](./tasks.md) (granular units + Loop AC)
> Generated by `mira-scaffold new-domain ${name} --tool-prefix ${prefix}` (ADR-016).

## Behavior / What

Deliver the **${name} domain specialist**: TODO(${name}) — one paragraph on the
domain, its source, and the questions it answers. Tools publish as typed MCP
contracts under the `${prefix}` prefix with fail-closed entitlements (ADR-031),
and the specialist is the next instantiation of the shared subgraph scaffold —
no new LangGraph wiring (ADR-014).

### Observable behaviors

1. **Source binding** — TODO(${name}): ${source_note}
2. **Typed MCP surface** — `${prefix}*` tools export as ADR-031 contracts
   (entitlement-bearing, read-only by default).
3. **Specialist reuse** — `build_${name}_specialist()` wraps `${upper}_DOMAIN`
   via `build_specialist_subgraph`; `${prefix}*` tools are invisible to other
   domains (fail-closed allow-listing).

## Acceptance Criteria

- [ ] TODO(${name}): source behaviours covered by tests
- [ ] `${prefix}*` tools export as typed, entitlement-bearing contracts
- [ ] `REPRESENTATIVE_${upper}_QUERY` runs end-to-end through the specialist
- [ ] Golden baseline registered (`evals/goldens/${name}.jsonl`) — ADR-045 gate
- [ ] Import isolation lint and full offline test suite pass
"""

_PLAN_TEMPLATE = """# ${title} Specialist Subgraph — Plan

> **Feature slug:** ${name}-specialist · Sibling spec: [`spec.md`](./spec.md) · Tasks: [`tasks.md`](./tasks.md)

## Depends On

| Dependency | Status | Notes |
|------------|--------|-------|
| ADR-013 / ADR-014 / ADR-020 / ADR-031 | Accepted | Shared specialist + connector foundations |
| ADR-016 Agent Scaffolding | Accepted | This trio was generated by `mira-scaffold` |

## Files

### Generated (this scaffold)

| Path | Purpose |
|------|---------|
${plan_files}

### To modify (wiring — see the specialist module docstring)

| Path | Change |
|------|--------|
| a registry wiring module (cf. `specialists/demo.py`) | Register the `${upper}_CARD` + factory |
| `evals/goldens/${name}.jsonl` | Promote the golden stub once end-to-end (ADR-045) |

## Edge cases

- TODO(${name}): source-specific malformed-input behaviour (raise, never a silent default).
- `${prefix}*` tools filtered out for non-${name} domains (fail-closed allow-listing).
"""

_TASKS_TEMPLATE = """# ${title} Specialist Subgraph — Tasks

> **Feature slug:** ${name}-specialist · Spec: [`spec.md`](./spec.md) · Plan: [`plan.md`](./plan.md)

Ordered implementation units over the generated skeleton.

---

## Task 1 — Source binding

TODO(${name}): ${source_note}

## Loop AC

- [ ] AC-1: source behaviours pass their tests
  - verify: `pytest ${test_paths} -q`
- [ ] AC-2: `${prefix}*` contracts are entitlement-bearing and read-only
  - verify: `pytest ${test_paths} -q`

---

## Task 2 — Specialist end-to-end

Replace the `REPRESENTATIVE_${upper}_QUERY` placeholder and implement the
`_infer_${name}_query` hook; promote the golden stub.

## Loop AC

- [ ] AC-1: representative query returns an attributed answer
  - verify: `pytest tests/test_${name}_specialist.py -q`
- [ ] AC-2: golden baseline gates in CI
  - verify: `pytest evals -q`
- [ ] AC-3: import isolation lint passes
  - verify: `python3 tools/lint_imports.py src/mira`
"""

_GOLDEN_TEMPLATE = (
    '{"id": "${name}-representative", '
    '"query": "TODO(${name}): representative query", '
    '"domain": "${name}", '
    '"expect": {"status": "sample"}}\n'
)


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------


def _render(template: str, **subs: str) -> str:
    return Template(template).substitute(**subs)


def _validate_name(name: str) -> str:
    if not _NAME_RE.fullmatch(name):
        raise ScaffoldError(
            f"domain name {name!r} must match [a-z][a-z0-9_]* (a Python module name)"
        )
    return name


def _normalize_prefix(tool_prefix: str) -> str:
    prefix = tool_prefix if tool_prefix.endswith(".") else f"{tool_prefix}."
    if not _PREFIX_RE.fullmatch(prefix):
        raise ScaffoldError(
            f"tool prefix {tool_prefix!r} must match [a-z][a-z0-9_.-]* "
            "(a trailing '.' is appended if missing)"
        )
    return prefix


def new_domain(
    name: str,
    tool_prefix: str,
    out: Path,
    *,
    domain_kind: str = "connector",
) -> list[Path]:
    """Generate every artifact for a new domain under ``out``; return the paths.

    Refuses to overwrite: if any target file already exists, raises
    :class:`ScaffoldError` and writes nothing.
    """
    name = _validate_name(name)
    prefix = _normalize_prefix(tool_prefix)
    if domain_kind not in ("connector", "mcp"):
        raise ScaffoldError(f"unknown --domain-kind {domain_kind!r} (connector|mcp)")

    source_type = prefix[:-1]
    subs = {
        "name": name,
        "prefix": prefix,
        "source_type": source_type,
        "upper": name.upper(),
        "title": name.replace("_", " ").title(),
        "class_name": "".join(part.title() for part in name.split("_")),
    }

    if domain_kind == "connector":
        specialist_docstring = _render(_SPECIALIST_DOCSTRING_CONNECTOR, **subs)
        source_note = (
            f"bind the `mira.connectors.{name}` connector skeleton to the real source"
        )
        plan_files = "\n".join(
            (
                f"| `src/mira/connectors/{name}.py` | Connector skeleton "
                f"(sample `lookup` capability, `{prefix}*` tool specs) |",
                f"| `src/mira/orchestration/specialists/{name}.py` | DomainSpec + "
                "specialist builder + inference hook stub |",
                f"| `tests/test_{name}_connector.py`, `tests/test_{name}_specialist.py` "
                "| Passing skeleton tests |",
            )
        )
        test_paths = f"tests/test_{name}_connector.py"
    else:
        specialist_docstring = _render(_SPECIALIST_DOCSTRING_MCP, **subs)
        source_note = (
            f"declare the MCP server in `MCP_SERVERS` and bind its `{prefix}*` tools"
        )
        plan_files = "\n".join(
            (
                f"| `src/mira/orchestration/specialists/{name}.py` | DomainSpec + "
                "specialist builder + inference hook stub (MCP-bound domain) |",
                f"| `tests/test_{name}_specialist.py` | Passing skeleton tests |",
            )
        )
        test_paths = f"tests/test_{name}_specialist.py"

    specialist_module = f'"""{specialist_docstring}"""' + _render(_SPECIALIST_BODY, **subs)

    doc_subs = {**subs, "source_note": source_note, "test_paths": test_paths}
    files: dict[Path, str] = {}
    if domain_kind == "connector":
        files[Path("src/mira/connectors") / f"{name}.py"] = _render(
            _CONNECTOR_TEMPLATE, **subs
        )
        files[Path("tests") / f"test_{name}_connector.py"] = _render(
            _CONNECTOR_TEST_TEMPLATE, **subs
        )
    files[Path("src/mira/orchestration/specialists") / f"{name}.py"] = specialist_module
    files[Path("tests") / f"test_{name}_specialist.py"] = _render(
        _SPECIALIST_TEST_TEMPLATE, **subs
    )
    spec_dir = Path("specs") / f"{name}-specialist"
    files[spec_dir / "spec.md"] = _render(_SPEC_TEMPLATE, **doc_subs)
    files[spec_dir / "plan.md"] = _render(_PLAN_TEMPLATE, **doc_subs, plan_files=plan_files)
    files[spec_dir / "tasks.md"] = _render(_TASKS_TEMPLATE, **doc_subs)
    files[Path("evals/goldens") / f"{name}.jsonl.example"] = _render(
        _GOLDEN_TEMPLATE, **subs
    )

    out = out.resolve()
    existing = [rel for rel in files if (out / rel).exists()]
    if existing:
        listing = ", ".join(str(rel) for rel in sorted(existing))
        raise ScaffoldError(
            f"refusing to overwrite existing files under {out}: {listing}"
        )

    written: list[Path] = []
    for rel, content in files.items():
        target = out / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(target)
    return sorted(written)


def main(argv: list[str] | None = None) -> int:
    """Console entry point for ``mira-scaffold``."""
    parser = argparse.ArgumentParser(
        prog="mira-scaffold",
        description="Generate Mira domain-agent artifacts (ADR-016).",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)
    new = subparsers.add_parser(
        "new-domain", help="Generate connector/specialist/tests/spec/golden artifacts"
    )
    new.add_argument("name", help="domain id, e.g. 'inventory' ([a-z][a-z0-9_]*)")
    new.add_argument(
        "--tool-prefix",
        required=True,
        help="MCP tool-name prefix for the domain allow-list, e.g. 'inventory.'",
    )
    new.add_argument(
        "--out",
        type=Path,
        default=Path.cwd(),
        help="repository root to generate into (default: current directory)",
    )
    new.add_argument(
        "--domain-kind",
        choices=("connector", "mcp"),
        default="connector",
        help="'connector' generates a local connector skeleton; "
        "'mcp' binds the domain to the declared MCP server registry instead",
    )
    args = parser.parse_args(argv)

    try:
        written = new_domain(
            args.name, args.tool_prefix, args.out, domain_kind=args.domain_kind
        )
    except ScaffoldError as exc:
        print(f"mira-scaffold: error: {exc}", file=sys.stderr)
        return 1

    for path in written:
        print(f"generated {path}")
    print(
        f"next: wire the agent card (see the specialist module docstring), then "
        f"promote evals/goldens/{args.name}.jsonl.example (ADR-045)."
    )
    return 0


__all__ = ["ScaffoldError", "main", "new_domain"]


if __name__ == "__main__":
    raise SystemExit(main())
